In [14]:
import os
import zipfile
from PIL import Image
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import cv2
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


# Path to the uploaded dataset zip file
zip_path = '/content/dataset-resized.zip'

# Temporary extraction path
extraction_path = 'path_to_extraction_folder'

# Extract the zip file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extraction_path)

# Define the path to the dataset folder
dataset_folder = os.path.join(extraction_path, "dataset-resized")

# List of categories (folder names)
categories = [dir_name for dir_name in os.listdir(dataset_folder) if not dir_name.startswith('.')]

# Initialize lists to store image data and labels
data = []
labels = []

# Define desired size of images (example: 128x128 pixels)
image_size = (128, 128)

# Loop through each category
for category in categories:
    category_folder = os.path.join(dataset_folder, category)
    print(f"Processing category: {category}")

    # Loop through each image file in the category folder
    for filename in tqdm(os.listdir(category_folder), desc=f"Loading {category}"):
        image_path = os.path.join(category_folder, filename)

        # Open the image using PIL and resize it
        with Image.open(image_path) as img:
            img_resized = img.resize(image_size)

        # Convert the image to a numpy array and normalize it
        image_array = np.array(img_resized) / 255.0

        # Append the processed image data and label to the lists
        data.append(image_array)
        labels.append(category)

# Convert lists to numpy arrays for machine learning processing
data = np.array(data)
labels = np.array(labels)

# Convert labels to numerical values using LabelEncoder
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(data, encoded_labels, test_size=0.2, random_state=42)

# You can now proceed with training your machine learning model
print("Data and labels prepared. Ready for model training.")


Processing category: paper


Loading paper: 100%|██████████| 594/594 [00:02<00:00, 200.89it/s]


Processing category: cardboard


Loading cardboard: 100%|██████████| 403/403 [00:02<00:00, 188.92it/s]


Processing category: trash


Loading trash: 100%|██████████| 137/137 [00:00<00:00, 245.16it/s]


Processing category: plastic


Loading plastic: 100%|██████████| 482/482 [00:01<00:00, 267.55it/s]


Processing category: metal


Loading metal: 100%|██████████| 410/410 [00:01<00:00, 267.12it/s]


Processing category: glass


Loading glass: 100%|██████████| 501/501 [00:01<00:00, 271.08it/s]


Data and labels prepared. Ready for model training.


In [12]:
import os
import numpy as np
import pandas as pd
from skimage.io import imread
from skimage.transform import resize
from tqdm import tqdm

# Corrected path to the dataset folder after extraction
base_path = '/content/path_to_extraction_folder/dataset-resized'  # Adjusted path

# Categories of the images
Categories = ['cardboard', 'glass', 'metal', 'paper', 'plastic', 'trash']

# Initialize lists to store flattened image data and corresponding labels
flat_data_arr = []
target_arr = []

# Loop through each category
for i in Categories:
    print(f'Loading... category : {i}')
    path = os.path.join(base_path, i)

    # Ensure the path exists before processing
    if os.path.exists(path):
        # Loop through each image file in the category folder
        for img in tqdm(os.listdir(path), desc=f'Loading {i}'):
            img_path = os.path.join(path, img)

            # Read the image, resize it to 150x150 pixels, and normalize the pixel values
            img_array = imread(img_path)
            img_resized = resize(img_array, (150, 150, 3))

            # Flatten the resized image and append it to the list, along with the label
            flat_data_arr.append(img_resized.flatten())
            target_arr.append(Categories.index(i))

        print(f'Loaded category: {i} successfully')
    else:
        print(f"Path does not exist: {path}")

# Convert lists to numpy arrays for further processing
flat_data = np.array(flat_data_arr)
target = np.array(target_arr)

# Create a DataFrame with the flattened image data
df = pd.DataFrame(flat_data)

# Add the target labels to the DataFrame
df['Target'] = target
df


Loading... category : cardboard


Loading cardboard: 100%|██████████| 403/403 [00:09<00:00, 43.68it/s]


Loaded category: cardboard successfully
Loading... category : glass


Loading glass: 100%|██████████| 501/501 [00:12<00:00, 40.08it/s]


Loaded category: glass successfully
Loading... category : metal


Loading metal: 100%|██████████| 410/410 [00:10<00:00, 40.17it/s]


Loaded category: metal successfully
Loading... category : paper


Loading paper: 100%|██████████| 594/594 [00:18<00:00, 32.26it/s]


Loaded category: paper successfully
Loading... category : plastic


Loading plastic: 100%|██████████| 482/482 [00:14<00:00, 33.66it/s]


Loaded category: plastic successfully
Loading... category : trash


Loading trash: 100%|██████████| 137/137 [00:03<00:00, 34.94it/s]


Loaded category: trash successfully


0         1         2         3         4         5         6  \
0     1.000000  1.000000  1.000000  1.000000  1.000000  1.000000  1.000000   
1     0.972549  0.835294  0.709804  0.972636  0.835381  0.709891  0.977250   
2     0.838479  0.720832  0.587499  0.834761  0.717114  0.583780  0.825568   
3     0.711760  0.352731  0.242158  0.825364  0.652418  0.556024  0.800122   
4     0.752532  0.576061  0.462336  0.752410  0.575939  0.462214  0.744871   
...        ...       ...       ...       ...       ...       ...       ...   
2522  0.886275  0.811765  0.752941  0.886275  0.811765  0.752941  0.886275   
2523  0.854902  0.780392  0.721569  0.854902  0.780392  0.721569  0.854902   
2524  0.940949  0.878203  0.827223  0.942480  0.879735  0.828755  0.934927   
2525  0.764766  0.647119  0.603982  0.764849  0.647202  0.604065  0.770005   
2526  0.925490  0.866667  0.784314  0.925532  0.866709  0.784356  0.928130   

             7         8         9  ...     67491     67492     67493  \
0     1.000000  1.000000  1.000000  ...  0.639704  0.514214  0.365194   
1     0.839995  0.714505  0.972150  ...  0.473269  0.394838  0.288955   
2     0.707920  0.574587  0.824405  ...  0.586051  0.554679  0.464483   
3     0.728429  0.663315  0.782666  ...  0.229110  0.127150  0.066609   
4     0.568401  0.454675  0.740665  ...  0.987297  0.966396  0.990784   
...        ...       ...       ...  ...       ...       ...       ...   
2522  0.811765  0.752941  0.886272  ...  0.324208  0.284993  0.237934   
2523  0.780392  0.721569  0.854902  ...  0.375047  0.327989  0.273087   
2524  0.872181  0.821201  0.929513  ...  0.854902  0.800000  0.756863   
2525  0.652358  0.609221  0.772543  ...  0.588666  0.502392  0.451411   
2526  0.869306  0.786953  0.929406  ...  0.338517  0.303223  0.244400   

         67494     67495     67496     67497     67498     67499  Target  
0     0.637421  0.511931  0.362912  0.639127  0.513637  0.364617       0  
1     0.465564  0.387133  0.281251  0.463920  0.385489  0.279607       0  
2     0.588217  0.556844  0.466648  0.569235  0.537863  0.447667       0  
3     0.242783  0.141565  0.072756  0.254131  0.155960  0.077926       0  
4     0.989720  0.960126  0.988277  0.995813  0.956995  0.988235       0  
...        ...       ...       ...       ...       ...       ...     ...  
2522  0.321611  0.282395  0.235336  0.321569  0.282353  0.235294       5  
2523  0.367348  0.320289  0.265387  0.358793  0.311734  0.256832       5  
2524  0.854902  0.800000  0.756863  0.854902  0.800000  0.756863       5  
2525  0.581770  0.495495  0.444515  0.567210  0.480936  0.429955       5  
2526  0.341075  0.305781  0.246957  0.341117  0.305822  0.246999       5  

[2527 rows x 67501 columns]

In [16]:
import cv2
from sklearn.metrics import confusion_matrix
# Function to extract color histograms from images
def extract_color_histogram(image_path, bins=32):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    hist = [cv2.calcHist([image], [i], None, [bins], [0, 256]) for i in range(3)]
    hist = np.concatenate([cv2.normalize(h, h).flatten() for h in hist])
    return hist
# Function to process images and extract features
def process_images(base_path):
    features = []
    labels = []
    categories = os.listdir(base_path)
    for category in categories:
        if category == ".DS_Store":
            continue
        category_path = os.path.join(base_path, category)
        images = [os.path.join(category_path, img) for img in os.listdir(category_path) if img.lower().endswith(('.png', '.jpg', '.jpeg'))]
        for image_path in images:
            hist_features = extract_color_histogram(image_path)
            features.append(hist_features)
            labels.append(category)
    return np.array(features), np.array(labels)
# Extract features and labels from the dataset
features, labels = process_images(base_path)
# Convert labels to numerical values
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, encoded_labels, test_size=0.2, random_state=42)
# Initialize the Logistic Regression classifier
log_reg_clf = LogisticRegression(max_iter=1000, random_state=42)
log_reg_clf.fit(X_train, y_train)
# Make predictions on the test set
y_pred = log_reg_clf.predict(X_test)
# Calculate accuracy and classification report
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=label_encoder.classes_)
print("Accuracy:", accuracy)
print("Classification Report:\n", report)
# Display the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy: 0.5612648221343873
Classification Report:
               precision    recall  f1-score   support

   cardboard       0.72      0.72      0.72        75
       glass       0.43      0.54      0.48        96
       metal       0.55      0.44      0.49        85
       paper       0.59      0.73      0.65       117
     plastic       0.58      0.49      0.53       100
       trash       0.47      0.21      0.29        33

    accuracy                           0.56       506
   macro avg       0.56      0.52      0.53       506
weighted avg       0.56      0.56      0.55       506

Confusion Matrix:
[[54  3 10  4  4  0]
 [ 3 52  6 17 15  3]
 [ 5 20 37 13  6  4]
 [ 4 14  5 85  8  1]
 [ 5 21  6 19 49  0]
 [ 4 12  3  5  2  7]]


In [17]:
from sklearn.decomposition import PCA
# Apply PCA to reduce the feature dimensionality
pca = PCA(n_components=0.95)  # Adjust this to the desired variance ratio
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)
# Initialize the Logistic Regression classifier
log_reg_clf = LogisticRegression(max_iter=1000, random_state=42)
log_reg_clf.fit(X_train_pca, y_train)
# Make predictions on the test set with PCA applied
y_pred_pca = log_reg_clf.predict(X_test_pca)
# Calculate accuracy and classification report
accuracy_pca = accuracy_score(y_test, y_pred_pca)
report_pca = classification_report(y_test, y_pred_pca, target_names=label_encoder.classes_)
print("PCA Accuracy:", accuracy_pca)
print("PCA Classification Report:\n", report_pca)
# Display the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))



PCA Accuracy: 0.5553359683794467
PCA Classification Report:
               precision    recall  f1-score   support

   cardboard       0.72      0.73      0.73        75
       glass       0.42      0.53      0.47        96
       metal       0.55      0.41      0.47        85
       paper       0.58      0.68      0.63       117
     plastic       0.56      0.53      0.54       100
       trash       0.58      0.21      0.31        33

    accuracy                           0.56       506
   macro avg       0.57      0.52      0.53       506
weighted avg       0.56      0.56      0.55       506

Confusion Matrix:
[[54  3 10  4  4  0]
 [ 3 52  6 17 15  3]
 [ 5 20 37 13  6  4]
 [ 4 14  5 85  8  1]
 [ 5 21  6 19 49  0]
 [ 4 12  3  5  2  7]]


In [18]:
from sklearn.metrics import confusion_matrix

# Calculate confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)

# Calculate sensitivity and specificity for each class
sensitivity_per_class = []
specificity_per_class = []
for i in range(conf_matrix.shape[0]):
    true_positives = conf_matrix[i, i]
    false_negatives = np.sum(conf_matrix[i, :]) - true_positives
    false_positives = np.sum(conf_matrix[:, i]) - true_positives
    true_negatives = np.sum(conf_matrix) - true_positives - false_negatives - false_positives

    sensitivity = true_positives / (true_positives + false_negatives)
    specificity = true_negatives / (true_negatives + false_positives)

    sensitivity_per_class.append(sensitivity)
    specificity_per_class.append(specificity)

# Calculate average sensitivity and specificity
average_sensitivity = np.mean(sensitivity_per_class)
average_specificity = np.mean(specificity_per_class)

print("Average Sensitivity:", average_sensitivity)
print("Average Specificity:", average_specificity)


Average Sensitivity: 0.5209296204884439
Average Specificity: 0.9095108357579401


In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
# Function to extract both RGB and HSV color histograms from images
def extract_features(image_path, bins=32):
    image = cv2.imread(image_path)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    hsv_image = cv2.cvtColor(image, cv2.COLOR_RGB2HSV)  # Convert to HSV
    # Calculate the histogram for RGB
    rgb_hist = np.concatenate([cv2.calcHist([image], [i], None, [bins], [0, 256]).flatten() for i in range(3)])
    # Calculate the histogram for HSV
    hsv_hist = np.concatenate([cv2.calcHist([hsv_image], [i], None, [bins], [0, 256]).flatten() for i in range(3)])
    # Concatenate RGB and HSV histograms into a single feature vector
    feature_vector = np.concatenate((rgb_hist, hsv_hist))
    return feature_vector
# Function to process images and extract features
def process_images(base_path, bins=32):
    features = []
    labels = []
    categories = os.listdir(base_path)
    for category in categories:
        if category == ".DS_Store" or category == '__MACOSX':
            continue
        category_path = os.path.join(base_path, category)
        images = [os.path.join(category_path, img) for img in os.listdir(category_path) if img.lower().endswith(('.png', '.jpg', '.jpeg'))]
        for image_path in images:
            feature_vector = extract_features(image_path, bins)
            features.append(feature_vector)
            labels.append(category)
    return np.array(features), np.array(labels)
# Extract features and labels from the dataset
features, labels = process_images(base_path)
# Convert labels to numerical values
label_encoder = LabelEncoder()
encoded_labels = label_encoder.fit_transform(labels)
# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, encoded_labels, test_size=0.2, random_state=42)
# Create a pipeline that includes scaling and logistic regression
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('logistic_regression', LogisticRegression(max_iter=1000))
])
# Define a range of hyperparameters for tuning
parameters = {
    'logistic_regression__C': np.logspace(-4, 4, 20),
    'logistic_regression__class_weight': [None, 'balanced'],
    'logistic_regression__solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
}
# Initialize GridSearchCV with the pipeline and hyperparameter space
grid_search = GridSearchCV(pipeline, parameters, cv=5, verbose=1, n_jobs=-1)
grid_search.fit(X_train, y_train)
# Retrieve the best hyperparameters and the corresponding best model
best_params = grid_search.best_params_
best_model = grid_search.best_estimator_
# Make predictions using the best model
y_pred = best_model.predict(X_test)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=label_encoder.classes_)
# Print the results
print(f"Best Parameters: {best_params}")
print("Accuracy:", accuracy)
print("Classification Report:\n", report)
# Display the confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Fitting 5 folds for each of 200 candidates, totalling 1000 fits
Best Parameters: {'logistic_regression__C': 1.623776739188721, 'logistic_regression__class_weight': None, 'logistic_regression__solver': 'liblinear'}
Accuracy: 0.6837944664031621
Classification Report:
               precision    recall  f1-score   support

   cardboard       0.78      0.83      0.80        75
       glass       0.61      0.65      0.63        96
       metal       0.76      0.55      0.64        85
       paper       0.71      0.80      0.75       117
     plastic       0.65      0.69      0.67       100
       trash       0.52      0.36      0.43        33

    accuracy                           0.68       506
   macro avg       0.67      0.65      0.65       506
weighted avg       0.68      0.68      0.68       506



In [20]:
import os
import pickle

# Assuming 'pipeline' is your trained model and 'metrics_results' is your computed metrics.

# Define the path for the combined pickle file
combined_file_path = '/content/combined_model_and_metrics.pkl'

# Create the directory if it does not exist
os.makedirs(os.path.dirname(combined_file_path), exist_ok=True)

# Combine the model and metrics into a dictionary
combined_data = {
    'model': pipeline,
    'metrics': classification_report
}

# Save the combined data to a single pickle file
with open(combined_file_path, 'wb') as combined_file:
    pickle.dump(combined_data, combined_file)

print(f'Combined model and metrics are saved at {combined_file_path}.')



Combined model and metrics are saved at /content/combined_model_and_metrics.pkl.
